In [2]:
import numpy as np
x=np.array([1,2,3],np.int16) # range of np.int16
print(x)
print(type(x))
print(x[0]);print(x[1]);print(x[2])
print(x[-1])
print(x[-2])
print(x[-3])

[1 2 3]
<class 'numpy.ndarray'>
1
2
3
3
2
1


In [5]:
#numpy iki boyutlu dizler
import numpy as np
x=np.array([[1,2,3],[4,5,6]],np.int16)
print(x)

print(x[0,0]);print(x[0,1]);print(x[0,2]);print("ccccccccc")
print(x[1,0]);print(x[1,1]);print(x[1,2]);print("ccccccccc")
print(x[:,0]);print(x[:,1]);print(x[:,2]);print("ccccccccc")# satırları tarayıp yalnızca yazdığın numaralı indisi alıyor
print("ccccc")
print(x[0,:]);print(x[1,:])# direkt satırları alıyor

[[1 2 3]
 [4 5 6]]
1
2
3
ccccccccc
4
5
6
ccccccccc
[1 4]
[2 5]
[3 6]
ccccccccc
ccccc
[1 2 3]
[4 5 6]


In [47]:
# numpy üç boyutlu diziler

import numpy as np 
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], np.int16)
print(x)
print("CCCCCC")
print(x[0:,1])# sadece birinci indisleri gir dedim eğer virgül bir değil direkt sıfır yaparsan zaten hepsini alıyor
print("CCCCCC")
print(x[0:,1,1])# 1 inci inddislerinde birinci indislerini aldık
print("CCCCCC")
print(x[0:1,1])# birinciyi direkt belirtip onun içindeki 1 i aldık
# yani bu şekilde virgülle başlayınca o an nereyi belirtiyosan ordan virgülden sonra belirttiğin indisleri çekiyor virgül ekledikçe daha derine gidiyor


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
CCCCCC
[[ 4  5  6]
 [10 11 12]]
CCCCCC
[ 5 11]
CCCCCC
[5]


In [54]:
# numpy ones and zeros
import numpy as np
x=np.empty([3,3],np.uint8)
print(x)
print("ccccccc")
y=np.full((3,3,3),dtype=np.int16,fill_value=10)
print(y)
print("ccccccc")
z=np.full((2,5,5),dtype=np.int16,fill_value=25)
print(z)

[[ 12   0 169]
 [169 178   2]
 [  0   0   0]]
ccccccc
[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]
ccccccc
[[[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]]
